## suppress inspection "UnusedProperty" for whole file
spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/probation
    username: postgres
    password: admin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.PostgreSQLDialect

exceptions:
  exception-map:
    not-found:
      code: 404
      message: "%s with id: %s - not found"
    bad-request:
      code: 400
      message: bad request
